version: 2

sources:
  - name: QWT_RAW
    database: "{{env_var('DBT_SOURCEDB', 'QWT_ANALYTICS')}}"
    schema: "{{env_var('DBT_SOURCESCHEMA', 'RAW')}}"
    tables:
        - name: customers
        - name: orders
        - name: orderdetails
        - name: suppliers
        - name: shipments

  - name: QWT_RAWGD
    database: "{{env_var('DBT_SOURCEDB', 'QWT_ANALYTICS')}}"
    schema: RAW_GD
    tables:
      - name: products