version: 2

sources:
  - name: QWT_RAW
    database: QWT_ANALYTICS
    schema: RAW
    tables:
        - name: customers
        - name: orders
        - name: orderdetails
        - name: suppliers
        - name: shipments

  - name: QWT_RAWGD
    database: QWT_ANALYTICS
    schema: RAW_GD
    tables:
      - name: products